//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Net;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "MD_CoopSoap", Namespace = "http://tempuri.org/")]
public partial class MD_Coop : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback CerrarSolicitudOperationCompleted;

    private System.Threading.SendOrPostCallback RecalcularSolicitudOperationCompleted;

    private System.Threading.SendOrPostCallback CrearSolicitudOperationCompleted;

    private System.Threading.SendOrPostCallback ObtenerCuotasOperationCompleted;

    /// <remarks/>
    public MD_Coop()
    {
        //this.Url = "https://dev.decisioncentre.com/app/HN_SagradaFamilia/MD_Coop.asmx"; //Primero                
        //this.Url = "https://www.transuniondecisioncentreuat.com.mx/LA/HN/sagrada-familia/MD_Coop.asmx"; //Desarrollo

        this.Url = "https://www.transuniondecisioncentre.com.mx/LA/HN/sagrada-familia/MD_Coop.asmx"; //Produccion real
        //Para implementar cambios de TransUnion en los protocolos el 30 de septiembre 2017
        System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
    }

    /// <remarks/>
    public event CerrarSolicitudCompletedEventHandler CerrarSolicitudCompleted;

    /// <remarks/>
    public event RecalcularSolicitudCompletedEventHandler RecalcularSolicitudCompleted;

    /// <remarks/>
    public event CrearSolicitudCompletedEventHandler CrearSolicitudCompleted;

    /// <remarks/>
    public event ObtenerCuotasCompletedEventHandler ObtenerCuotasCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CerrarSolicitud", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CerrarSolicitud(string XML)
    {
        object[] results = this.Invoke("CerrarSolicitud", new object[] {
                    XML});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCerrarSolicitud(string XML, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CerrarSolicitud", new object[] {
                    XML}, callback, asyncState);
    }

    /// <remarks/>
    public string EndCerrarSolicitud(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void CerrarSolicitudAsync(string XML)
    {
        this.CerrarSolicitudAsync(XML, null);
    }

    /// <remarks/>
    public void CerrarSolicitudAsync(string XML, object userState)
    {
        if ((this.CerrarSolicitudOperationCompleted == null))
        {
            this.CerrarSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCerrarSolicitudOperationCompleted);
        }
        this.InvokeAsync("CerrarSolicitud", new object[] {
                    XML}, this.CerrarSolicitudOperationCompleted, userState);
    }

    private void OnCerrarSolicitudOperationCompleted(object arg)
    {
        if ((this.CerrarSolicitudCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CerrarSolicitudCompleted(this, new CerrarSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecalcularSolicitud", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string RecalcularSolicitud(string XML)
    {
        object[] results = this.Invoke("RecalcularSolicitud", new object[] {
                    XML});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginRecalcularSolicitud(string XML, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("RecalcularSolicitud", new object[] {
                    XML}, callback, asyncState);
    }

    /// <remarks/>
    public string EndRecalcularSolicitud(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void RecalcularSolicitudAsync(string XML)
    {
        this.RecalcularSolicitudAsync(XML, null);
    }

    /// <remarks/>
    public void RecalcularSolicitudAsync(string XML, object userState)
    {
        if ((this.RecalcularSolicitudOperationCompleted == null))
        {
            this.RecalcularSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecalcularSolicitudOperationCompleted);
        }
        this.InvokeAsync("RecalcularSolicitud", new object[] {
                    XML}, this.RecalcularSolicitudOperationCompleted, userState);
    }

    private void OnRecalcularSolicitudOperationCompleted(object arg)
    {
        if ((this.RecalcularSolicitudCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RecalcularSolicitudCompleted(this, new RecalcularSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearSolicitud", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CrearSolicitud(string XML)
    {
        object[] results = this.Invoke("CrearSolicitud", new object[] {
                    XML});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCrearSolicitud(string XML, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CrearSolicitud", new object[] {
                    XML}, callback, asyncState);
    }

    /// <remarks/>
    public string EndCrearSolicitud(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void CrearSolicitudAsync(string XML)
    {
        this.CrearSolicitudAsync(XML, null);
    }

    /// <remarks/>
    public void CrearSolicitudAsync(string XML, object userState)
    {
        if ((this.CrearSolicitudOperationCompleted == null))
        {
            this.CrearSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearSolicitudOperationCompleted);
        }
        this.InvokeAsync("CrearSolicitud", new object[] {
                    XML}, this.CrearSolicitudOperationCompleted, userState);
    }

    private void OnCrearSolicitudOperationCompleted(object arg)
    {
        if ((this.CrearSolicitudCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CrearSolicitudCompleted(this, new CrearSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCuotas", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ObtenerCuotas(string XML)
    {
        object[] results = this.Invoke("ObtenerCuotas", new object[] {
                    XML});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginObtenerCuotas(string XML, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ObtenerCuotas", new object[] {
                    XML}, callback, asyncState);
    }

    /// <remarks/>
    public string EndObtenerCuotas(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void ObtenerCuotasAsync(string XML)
    {
        this.ObtenerCuotasAsync(XML, null);
    }

    /// <remarks/>
    public void ObtenerCuotasAsync(string XML, object userState)
    {
        if ((this.ObtenerCuotasOperationCompleted == null))
        {
            this.ObtenerCuotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCuotasOperationCompleted);
        }
        this.InvokeAsync("ObtenerCuotas", new object[] {
                    XML}, this.ObtenerCuotasOperationCompleted, userState);
    }

    private void OnObtenerCuotasOperationCompleted(object arg)
    {
        if ((this.ObtenerCuotasCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObtenerCuotasCompleted(this, new ObtenerCuotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CerrarSolicitudCompletedEventHandler(object sender, CerrarSolicitudCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CerrarSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    private object[] results;

    internal CerrarSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void RecalcularSolicitudCompletedEventHandler(object sender, RecalcularSolicitudCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RecalcularSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    private object[] results;

    internal RecalcularSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CrearSolicitudCompletedEventHandler(object sender, CrearSolicitudCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CrearSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    private object[] results;

    internal CrearSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void ObtenerCuotasCompletedEventHandler(object sender, ObtenerCuotasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObtenerCuotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    private object[] results;

    internal ObtenerCuotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
